on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy blog into Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        run: pnpm install
      - name: Build app
        run: pnpm exec nx run realm:build-cloudflare
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: realm-blog
          directory: dist/apps/realm
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
